# Generated by Django 5.1.1 on 2024-09-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCountyTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='assistant',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='province',
        ),
        migrations.AlterField(
            model_name='assistant',
            name='city_county_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='assistant.citycountytown'),
        ),
        migrations.AddField(
            model_name='citycountytown',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='assistant.province'),
        ),
    ]
