# Generated by Django 5.1.1 on 2024-09-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_citycountytown_province_rename_title_assistant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='assistant_variable',
            field=models.CharField(default='default_assistant', max_length=255),
        ),
        migrations.AddField(
            model_name='assistant',
            name='country',
            field=models.CharField(default='한국', max_length=100),
        ),
        migrations.AddField(
            model_name='assistant',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistant.province'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='city_county_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.citycountytown'),
        ),
    ]
