# Generated by Django 4.2.16 on 2024-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistant_question_1_assistant_question_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='welcome_message',
            field=models.TextField(default='환영합니다! 무엇을 도와드릴까요?'),
        ),
    ]
