# Generated by Django 5.1.1 on 2024-09-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistant_assistant_variable_assistant_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='assistant_photos/'),
        ),
    ]
