# Generated by Django 5.1.1 on 2024-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_assistant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='country',
            field=models.CharField(default='대한민국', max_length=100),
        ),
    ]
