# Generated by Django 4.2.16 on 2024-09-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_assistant_vector_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='vector_store_id',
        ),
    ]
